# 
# @description       : Retrieves an unused scratch org from the pool and emails login
#                      details to the username specified
# @author            : Lawrence Newcombe
#
# Modifications Log 
# Ver   Date         Author             Modification
# 1.0   05-03-2020   Lawrence Newcombe  Initial Version
# 

name: Fetch a Scratch Org for Development

on:
  workflow_dispatch:
    inputs:
      dev_username:
        description: 'Your username in production'
        required: true

env:
  DEV_USERNAME: ${{ github.event.inputs.dev_username }}
  JWT_SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}
  CONSUMER_KEY: ${{ secrets.CONNECTED_APP_CONSUMER_KEY }}
  DEV_HUB_USERNAME: ${{ secrets.DEV_HUB_USERNAME}}
  POOL_NAME: 'Dev_pool'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    # Command below is taken from approach in trailheadapps repo https://github.com/trailheadapps/automation-components/actions/runs/106422605/workflow
    - name: Install Salesforce CLI
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir sfdx-cli
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
        ./sfdx-cli/install

    # Checkout the code in the pull request
    - name: 'Checkout source code'
      uses: actions/checkout@v2

    - name: List directory
      run: |
        ls

    # Call a sub-action (from scripts subdirectory) to install DX
    - uses: actions/checkout@v2
    - id: foo
      uses: ./.github/workflows/scripts/install-and-authenticate-dx
      with:
        jwt-signing-key: ${{ secrets.JWT_SIGNING_KEY }}
        consumer-key: ${{ secrets.CONNECTED_APP_CONSUMER_KEY }}
        dev-hub-username: ${{ secrets.DEV_HUB_USERNAME}}

    # Install SFPowerKit SFDX extension https://github.com/Accenture/sfpowerkit
    - name: Install sfpowerkit
      run: |
        echo 'y' | sfdx plugins:install sfpowerkit

    - name: Check current contents of pool
      run: |
        sfdx sfpowerkit:pool:list --tag=$POOL_NAME --allscratchorgs

    - name: Fetch an org from the pool
      run: |
        sfdx sfpowerkit:pool:fetch --tag=$POOL_NAME -s $DEV_USERNAME

    - name: Check new contents of pool
      run: |
        sfdx sfpowerkit:pool:list --tag=$POOL_NAME --allscratchorgs