# Prepare scratch orgs
# Create and deploy managed packages to orgs so that they're ready to use with sfpowerscripts 

name: Prepare Scratch Orgs

on:
  workflow_dispatch:
    inputs:
      no_orgs_in_pool:
        description: 'Number of scratch orgs to prepare in the pool'
        required: true
        default: '5'

env:
  JWT_SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}
  CONSUMER_KEY: ${{ secrets.CONNECTED_APP_CONSUMER_KEY }}
  DEV_HUB_USERNAME: ${{ secrets.DEV_HUB_USERNAME}}
  NO_ORGS_IN_POOL: ${{ github.event.inputs.no_orgs_in_pool }}
  POOL_NAME: 'Dev_pool'
  CONFIG_FILE: 'scratchorg-poolconfig.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    # Command below is taken from approach in trailheadapps repo https://github.com/trailheadapps/automation-components/actions/runs/106422605/workflow
    - name: Install Salesforce CLI
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir sfdx-cli
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
        ./sfdx-cli/install

    - name: Authenticate and set default DevHub
      run: |
        echo "${JWT_SIGNING_KEY}" > server.key
        sfdx force:auth:jwt:grant --clientid $CONSUMER_KEY --jwtkeyfile server.key --username $DEV_HUB_USERNAME --setdefaultdevhubusername -a devhub

    # Install SFPowerKit SFDX extension https://github.com/Accenture/sfpowerkit
    - name: Install sfpowerkit
      run: |
        echo 'y' | sfdx plugins:install sfpowerkit

    - name: Check current contents of pool
      run: |
        sfdx sfpowerkit:pool:list --tag=$POOL_NAME --allscratchorgs

    - name: Remove any orgs already in pool
      run: |
        sfdx sfpowerkit:pool:delete --tag=$POOL_NAME
        echo "Cleared scratch org pool $POOL_NAME"

    - name: Create pool with required number of orgs
      run: |
        sfdx sfpowerkit:pool:create --configfilepath=$CONFIG_FILE --targetdevhubusername=devhub
    
    - name: Check new contents of pool
      run: |
        sfdx sfpowerkit:pool:list --tag=$POOL_NAME --allscratchorgs